# Generated by Django 4.2.7 on 2026-03-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(choices=[('peito', 'Peito'), ('costas', 'Costas'), ('ombros', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('abdomen', 'Abdômen'), ('gluteos', 'Glúteos'), ('quadriceps', 'Quadríceps'), ('posterior', 'Posterior de coxa'), ('panturrilha', 'Panturrilha'), ('cardio', 'Cardio'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticoes', models.CharField(default='12', help_text='Ex: 12 ou 8-12', max_length=20)),
                ('carga', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('descanso', models.PositiveIntegerField(default=60, help_text='segundos')),
                ('observacoes', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treino')),
            ],
            options={
                'verbose_name': 'Exercício do Treino',
                'verbose_name_plural': 'Exercícios do Treino',
                'ordering': ['ordem'],
            },
        ),
    ]
